productos = [
        {'id': 1,
        'nombre': 'Flan borracho',
        'descripcion': 'Postre a base de leche y ron',
        'imagen_url': 'https://mojo.generalmills.com/api/public/content/nVkc4H0aVkCcWbegp426XA_gmi_hi_res_jpeg.jpeg',
        'precio': 3000},
        {'id': 2,
        'nombre': 'Flan napolitano',
        'descripcion': 'Postre a base de leche y huevo',
        'imagen_url': 'https://mojo.generalmills.com/api/public/content/8uZmUSTUo0u6KSltqq0cxw_gmi_hi_res_jpeg.jpeg',
        'precio': 3200},
        {'id': 3,
        'nombre': 'Panna Cotta de Mandarina',
        'descripcion': 'Panna cota con salsa de mandarina',
        'imagen_url': 'https://mojo.generalmills.com/api/public/content/Ffusy4LXdEW6O5WqcD7Ygw_gmi_hi_res_jpeg.jpeg',
        'precio': 4000},
        {'id': 4,
        'nombre': 'Flan de Banana',
        'descripcion': 'Flan de plátano y vanilla',
        'imagen_url': 'https://mojo.generalmills.com/api/public/content/koKeX7iUKkWrNiYXLsHp8Q_gmi_hi_res_jpeg.jpeg',
        'precio': 2500},
]